services:
  neo4j-db:
    image: neo4j:5.23
    container_name: neo4j-db
    environment:
      - NEO4J_AUTH=neo4j/my_neo4j_password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

  kg-builder-app:
    build: .
    container_name: kg-builder-app
    command: tail -f /dev/null
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - neo4j-db
      - ollama
    networks:
      - app-network

  api:
    build: .
    container_name: rag-api
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - kg-builder-app
      - neo4j-db
      - ollama
    ports:
      - "8000:8000"
    networks:
      - app-network

volumes:
  neo4j_data:
  ollama_data:

networks:
  app-network:
    external: false
